### ISSUE TITLE
Misleading information about bed friction in the screen output

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#191]
@donghuix reported the following screen output, which is misleading because bed friction is always turned on.

```
DETAIL: Physics:
DETAIL:   Flow:
DETAIL:     Bed friction: disabled
DETAIL:   Sediment model: disabled
DETAIL:   Salinity model: disabled
```

@jeff-cohere, We had previously discussed that will support multiple bed friction models that will be added in the `.yaml` as

```
bed_friction: <wylie93/xia18>
```

At present, we only support the `wylie93` bed friction term. So, how about we change the screen output to the following?

```
DETAIL: Physics:
DETAIL:   Flow:
DETAIL:     Bed friction model: Wylie93
```

**Comment by jeff-cohere** [comment]
Sounds good to me! This is just an oversight, so we can easily fix this.

**Comment by jeff-cohere** [comment]
One question: I see that we support the Wylie93 model, but we allow it to be enabled or disabled via a boolean flag. It seems like @donghuix was running with bed friction disabled--otherwise it would have printed `enabled` instead of `disabled`.

Is this the case? If not, we have another thing to fix. If so, all we need to do is print `Wylie93` instead of `enabled` when the flag is true.

**Comment by donghuix** [comment]
FYI, below is my .ymal file and I didn't setup the friction option.

```
physics:
  flow:
    mode: swe

numerics:
  spatial: fv
  temporal: euler
  riemann: roe

logging:
  level: debug

time:
  final_time       : 36000
  time_step        : 1.0
  coupling_interval: 60.0
  unit             : seconds

output:
  format: xdmf
  interval: 3600
  batch_size: 10
  time_series:
    boundary_fluxes: 1

grid:
  file: sanjacinto_test.exo

# one region represents the whole domain
regions:
  - name: domain
    grid_region_id: 1

surface_composition:
  - region: domain
    material: smooth

materials:
  - name: smooth
    properties:
      manning:
        value: 0.015

initial_conditions:
  - region: domain
    flow: domain_flow_ic

boundaries:
  - name: bottom_wall
    grid_boundary_id: 1

boundary_conditions:
  - boundaries: [bottom_wall]
    flow: outflow_bc

flow_conditions:
  - name: domain_flow_ic
    type: dirichlet
    file: sanjacinto_test.ic.int32.bin
    format: binary
  - name: outflow_bc
    type: dirichlet
    height: 0
    x_momentum: 0
    y_momentum: 0
```
