### ISSUE TITLE
Migrate rainfall data handling from driver to RDycore

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#199]
RDycore supports constant, spatially-homogeneous, and spatially-hetergeneous rainfall read from rectinlinear grids within given data files. However, the logic for handling this data is implemented entirely within the standalone drivers. It would be good to incorporate this rainfall data into RDycore's YAML input file.

Looking at our existing input specs for [sources](https://rdycore.github.io/RDycore/common/input.html#sources) and [flow conditions](https://rdycore.github.io/RDycore/common/input.html#flow_conditions), it's not immediately clear to me how best to patch in rainfall contributions. Ostensibly rainfall would increase the water's height without affecting sediment or salinity content. But if we add some option to include rainfall in a source condition, we can add a `[rainfall]` section that describes rainfall in terms that are equivalent to the constant, homogeneous, and heterogeneous configurations now implemented in the driver:

```
rainfall:
  constant: <rate>   # only one of constant, homogeneous, heterogeneous may be given
  homogeneous:
    file: homogeneous-rainfall.tsv
    interpolate: <true/false>
  heterogeneous:
    file: heterogeneous-rainfall-tsv  # <-- might actually need a directory of files
    start_date: <date>
```
