### ISSUE TITLE
Specify initial condition from RDycore's output .h5 file

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#297]
Presently, we only support IC from a file in a binary format line:

```yaml
    flow_conditions:
    - name: domain_flow_ic
      type: dirichlet
      file: Differnt.Houston1km.ic.${PETSC_ID_TYPE}.bin
      format: binary
```
where `Differnt.Houston1km.ic.${PETSC_ID_TYPE}.bin` is in a PETSc binary format.

An example of RDycore .h5 output file is as:
```
h5dump -H output/quad_tri_mesh-0.h5
HDF5 "output/quad_tri_mesh-0.h5" {
GROUP "/" {
   GROUP "1 5.000000E-04 sec" {
      DATASET "Height" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 12 ) / ( 12 ) }
      }
      DATASET "MomentumX" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 12 ) / ( 12 ) }
      }
      DATASET "MomentumY" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 12 ) / ( 12 ) }
      }
      DATASET "Parameter" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SIMPLE { ( 12 ) / ( 12 ) }
      }
   }
```

Following is the suggested yaml block to specify IC from RDycore's output file:
```yaml
    flow_conditions:
    - name: domain_flow_ic
      type: dirichlet
      file: output/quad_tri_mesh-0.h5
      format: rdycore_h5_output
      h5_group_name: "1 5.000000E-04 sec"
```
