### ISSUE TITLE
Add `regions` and `boundaries` YAML sections to assign names to regions and boundaries

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#96]
Getting initial and boundary conditions correct is one of the trickier parts of running simulations. To aid users in this task, we will create a couple of new sections in our YAML input specification that allow us to associate a human-readable name with regions (disjoint sets of cells) and boundaries (disjoint sets of edges)

## Regions

A `regions` section lists all regions, associating a name with the region IDs parsed by PETSc from the underlying mesh file: Regions need not be listed in the order in which they are numbered in the mesh.

```
# e.g. for the dam problem (ex2b.yaml)
regions:
  - name: downstream   # human-readable name for the region
    mesh_region_id: 2    # mesh identifier for the region
  - name: upstream 
    mesh_region_id: 1
```

Then initial conditions can be assigned to regions thus:

```
...
initial_conditions:
  regions:
    - region: upstream
      flow: dam_top_ic
    - region: downstream
      flow: dam_bottom_ic
```

## Boundaries

Similarly, a `boundaries` section lists all boundaries, associating a name with the boundary IDs parsed by PETSc from the underlying mesh file. And similarly, these boundaries need not be listed in any particular order.

```
# e.g. ex2b.yaml
boundaries:
  - name: bottom_wall
    mesh_boundary_id: 3  # mesh identifier for the boundary
  - name: top_wall
    mesh_boundary_id: 2
  - name: exterior
    mesh_boundary_id: 1
```

Then boundary conditions can be assigned to boundaries in a nice human-readable form (additionally assigning a name to the boundary condition):

```
boundary_conditions:
  - name: my_favorite_bc
     boundary: top_wall
     flow: reflecting_bc
  - name: your_favorite_bc
     boundary: bottom_wall
     flow: outflow_bc
```

## Extra Credit

We could even allow the `boundaries` section to group a set of boundaries into a single named conceptual boundary, treating them as a union of sets of edges.

```
boundaries:
 - name: north
   mesh_boundary_id: 1
 - name: south
   mesh_boundary_id: 3
 - name: east
   mesh_boundary_id: 2
 - name: west
   mesh_boundary_id: 4
 - name: north_and_west
   union: [north, west]
 - name: south_and_east
   union: [south, east]
```

The same could be done for regions, of course.

**Comment by jeff-cohere** [comment]
Thinking about this a bit more, I think I'd rather preserve the disjointedness of boundaries, since disjoint sets are easier to reason about in general. This precludes the change described in the "extra credit" section above.

To make it easier to assign a boundary condition to multiple boundaries, we could instead replace the `boundary` field of `boundary_conditions` with a `boundaries` field that is a sequence of boundary names, e.g.

```
boundary_conditions:
  - name: my_favorite_bc
     boundaries: ['top_wall', 'exterior']
     flow: reflecting_bc
  - name: your_favorite_bc
     boundaries: ['bottom_wall']
     flow: outflow_bc

```

The need to quote the boundary names in the above syntax is an unfortunate, uh, "tick." But I think it's still pretty clear. Additionally, the use of a sequence of boundary names in the general case emphasizes that boundary conditions and boundaries have a one-to-many relationship, which isn't always obvious. For example, @bishtgautam had to remind me that all boundaries without specified boundary conditions get associated with the same "auto-generated" reflecting boundary condition.

**Comment by jeff-cohere** [comment]
Hmm. One possibility that arises when we explicitly list regions and boundaries and associate them with mesh-assigned IDs is that we can reduce the complexity of specifying initial conditions and sources via files. Currently, the `initial_conditions` and `sources` sections each have two subsections:

1. `domain`: includes `file` and `format` fields that specify the name of a file and its format, for reading data from a file to the entire computational domain
2. `regions`: includes region-wise initial conditions/sources

With a little bit of work, we could allow data to be read on a per-region or per-boundary basis from a file. This would only pertain to `dirichlet`-type initial/boundary conditions and sources, as it is with initial conditions currently. We could add `file` and `format` fields to the `flow_conditions`, `sediment_conditions`, and `salinity_conditions` sections that, when specified, would indicate that the data for these conditions would be drawn from a file in the specified format.

If we delegate this information to flow, sediment, and salinity conditions themselves, we can eliminate the `domain` subsection from the `initial_conditions` and `source` sections, and use by-region specification for these things:

```
initial_conditions:
  - region: upstream
    flow: dam_top_ic
    sediment: domain_sediment_ic
  - region: downstream
    flow: dam_bottom_ic
    sediment: domain_sediment_ic
```

In this case, suppose there's a sediment condition called `domain_sediment_ic` with `file` and `format` fields that identify a domain-wide data file for populating sediment initial conditions. For each region, RDycore would extract the data from this file only to the cells that belong to the region. If this sediment IC is referred to in every region in the domain, the sediment initial conditions are populated everywhere in the domain. We could also draw boundary condition data from files if we wanted to, though it's less clear to me how helpful this would be.

This change has some nice features:

* it simplifies the structure of the `initial_conditions` and `sources` input sections
* it allows us to use files to selectively populate regions with data, which makes it easier to prepare test and simulation data
* it may be even be possible to create a mapping between unrefined file data and refined cells, which overcomes a limitation of the current `domain` approach to initial conditions and sources.
* conceptually, it seems simpler to me to have the flow/sediment/salinity conditions store their data or its location

I just wanted to write these thoughts down for possible discussion.
